language: php
php:
  - 7.2

before_script:
  - composer install
  - composer test

script:
  - composer coverage_clover
  - composer require --dev php-coveralls/php-coveralls

after_script:
  - travis_retry php vendor/bin/php-coveralls -v